trigger:
  branches:
    include:
      - main

pool: HTML-CI-Pipeline

steps:
  - checkout: self
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: '$(Build.SourcesDirectory)'
      includeRootFolder: false
      archiveType: 'zip'
      archiveFile: '$(Build.ArtifactStagingDirectory)/spl.zip'
  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: 'ssh-comms'
      sourceFolder: '$(Build.ArtifactStagingDirectory)'
      contents: 'spl.zip'
      targetFolder: '/home/azureuser/spl'
  - task: SSH@0
    inputs:
      sshEndpoint: 'ssh-comms'
      runOptions: 'commands'
      commands: |
        cd /home/azureuser/spl
        unzip spl.zip
        rm spl.zip
        sudo cp -r /home/azureuser/spl/* /var/www/html/
        sudo systemctl restart nginx